### ISSUE TITLE
Make the scripts more general

### ISSUE THREAD

**Issue by JorgeFernandes-Git** [miguelriemoliveira/rosbag_tools#1]
The tools created here were developed to fix a specific [bag file](https://github.com/JorgeFernandes-Git/zau_bot/issues/21#issuecomment-1564240080), but most of these tools can be used for other situations with little to no adaptation of the code.

We can implement a set of input args to make it easy to adapt.

**Comment by miguelriemoliveira** [comment]
Right. That's what I did in the scripts I developed.

**Comment by JorgeFernandes-Git** [comment]
I have to implement some improvements. 
But they are done.

I also update the readme.
