### ISSUE TITLE
New script - rename_tf_frames

### ISSUE THREAD

**Issue by Kazadhum** [miguelriemoliveira/rosbag_tools#3]
Hi @miguelriemoliveira. I've noticed that there wasn't a script written that renamed the /tf frames in a bagfile yet, so I wrote one and it seems to be working correctly. I'm not a collaborator yet, so I can't add it. Could you invite me?

Additionally, would you rather I just push it to the main branch or create a new branch and pull request?

**Comment by miguelriemoliveira** [comment]
Thanks for the contribution!
